### ISSUE TITLE
wording around steps

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/opendronemap-ecs#13]
#8 introduced a problem with wording because the subitems are named "step 1..." but the original wording of steps referred to the higher level items

**Comment by danbjoseph** [comment]
where i've referenced "steps" in the subitems it's the the stages as labelled in the AWS setup process
<img width="982" alt="screen shot 2017-12-24 at 9 19 41 am" src="https://user-images.githubusercontent.com/4806884/34450578-ed40a10c-ecda-11e7-964f-dad727ac7c49.png">

**Comment by matthewberryman** [comment]
I know, but I had separately written "at the end of step 1" for example that then no longer made sense in light of your changes.
