### ISSUE TITLE
/code/s3.sh: line 3: s3cmd: command not found

### ISSUE THREAD

**Issue by spenrose** [smart-facility/opendronemap-ecs#23]
I am trying to get this running and once my task kicks off the container running in my ec2 instance spits out these logs. It looks like it is missing the `s3cmd` tool. I wasn't able to find the docker file that is powering the container to see if this is installed. Any advice?

```
/code/s3.sh: line 3: s3cmd: command not found
[94m[INFO] Initializing OpenDroneMap app - Wed May 09 06:01:26 2018[0m
[94m[INFO] Running ODM Load Dataset Cell[0m
[94m[INFO] Project directory /code/images doesn't exist. Creating it now. [0m
[92m[DEBUG] /code/images[0m
[92m[DEBUG] Loading dataset from: /code/images[0m
[92m[DEBUG] /code/images[0m
[91m[ERROR] Not enough supported images in /code/images[0m
[94m[INFO] OpenDroneMap app finished - Wed May 09 06:01:26 2018[0m
/code/s3.sh: line 5: s3cmd: command not found
/code/s3.sh: line 6: s3cmd: command not found
```

**Comment by matthewberryman** [comment]
^^ this is the repo I'm building from and as you can see I've opened and resolved the issue there—the install of s3cmd was lost in a merge. I will close this issue once the image is built and pushed.

**Comment by spenrose** [comment]
Awesome. Thanks for the quick fix!
